In [120]:
import numpy as np

In [121]:
hurricane = np.array([3,-5,5])

In [122]:
island = np.array([-5,4,0])

In [129]:
destroyed = np.array([[[4,-3,1],[5,5,2]],[[-1,-2,2],[2,-3,0]], [[-1,-4,2],[0,-4,-1]]])

In [124]:
the = np.array([[1, 0,0], [0,1,0], [0,0,1]])

In [125]:
the_hurricane = np.matmul(the, hurricane)

In [130]:
the_hurricane_destroyed = np.tensordot(the_hurricane, destroyed, axes=1)

In [131]:
the_hurricane_destroyed

array([[ 12, -19,   3],
       [  5,  10,   1]])

In [134]:
collapsed_destroyed = destroyed[:,0,:] + destroyed[:,1,:]

In [135]:
collapsed_destroyed

array([[ 9,  2,  3],
       [ 1, -5,  2],
       [-1, -8,  1]])

In [138]:
hurricane_destroyed = np.matmul(hurricane, collapsed_destroyed)

In [139]:
island * hurricane_destroyed

array([-85, -36,   0])